services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/app
    tty: true
    image: murder-mystery-note
    container_name: murder-mystery-note-container
    environment:
      TZ: 'Asia/Tokyo'
    network_mode: 'host'
