name: Deploy Preview

on:
  push:
    branches:
      - 'feature/**'

jobs:
  preview:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy action
        uses: ./.github/actions/deploy
        with:
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
